apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-gcp-network
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-gcp-network
    meta.crossplane.io/license: Apache-2.0

spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-gcp-compute
      # renovate: datasource=github-releases depName=upbound/provider-gcp
      version: "v0.41.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.2.1"
