apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: networks.gcp.platform.upbound.io
spec:
  scope: Namespaced
  group: gcp.platform.upbound.io
  names:
    kind: Network
    plural: networks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: Network Parameters
                  properties:
                    id:
                      type: string
                      description: ID of this Network that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    managementPolicies:
                      description: ManagementPolicies for the resources. Defaults to ["*"] which includes all operations.
                      type: array
                      items:
                        type: string
                        enum:
                          - "*"
                          - Create
                          - Observe
                          - Update
                          - Delete
                          - LateInitialize
                      default: ["*"]
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                  required:
                    - managementPolicies
                    - providerConfigName
                    - id
                    - region
                  type: object
              required:
                - parameters
