apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.gcp.platform.upbound.io
spec:
  group: gcp.platform.upbound.io
  names:
    kind: XNetwork
    plural: xnetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  description: Network Parameters
                  properties:
                    id:
                      type: string
                      description: ID of this Network that other objects will use to refer to it.
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    deletionPolicy:
                      description: When the Composition is deleted, delete the GCP resources. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                  required:
                    - deletionPolicy
                    - providerConfigName
                    - id
                    - region
                  type: object
              required:
                - parameters
