apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.gcp.platform.upbound.io
  labels:
    provider: gcp
    type: basic
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: gcp.platform.upbound.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: upbound-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: providerConfigRef
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
          - name: deletionPolicy
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
          - name: region
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region
        resources:
          - name: network
            base:
              apiVersion: compute.gcp.upbound.io/v1beta1
              kind: Network
              spec:
                forProvider:
                  autoCreateSubnetworks: false
                  routingMode: REGIONAL
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.labels[networks.gcp.platform.upbound.io/network-id]

          - name: subnetwork
            base:
              apiVersion: compute.gcp.upbound.io/v1beta1
              kind: Subnetwork
              spec:
                forProvider:
                  ipCidrRange: 172.16.0.0/16
                  networkSelector:
                    matchControllerRef: true
                  privateIpGoogleAccess: true
                  secondaryIpRange:
                    - ipCidrRange: 10.200.0.0/14
                      rangeName: pods
                    - ipCidrRange: 10.204.0.0/16
                      rangeName: services
            patches:
              - type: PatchSet
                patchSetName: providerConfigRef
              - type: PatchSet
                patchSetName: deletionPolicy
              - type: PatchSet
                patchSetName: region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.id
                toFieldPath: metadata.labels[networks.gcp.platform.upbound.io/network-id]
