apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.gcp.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: gcp.platform.upbound.io/v1alpha1
    kind: XNetwork
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-demo-configuration-gcp-networkxnetwork
    step: xnetwork
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
